name: ecoweb

type: php:8.1

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv
        - pdo_pgsql
        

#variables:
#    php:
#        # uncomment on PHP 7.4+
#        #opcache.preload: config/preload.php

build:
    flavor: none

relationships:
    database: "database:postgresql"

disk: 512

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

mounts:
    "/var": { source: local, source_path: var }

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | bash
        symfony-build

    deploy: |
        set -x -e

        symfony-deploy

